### ISSUE TITLE
Prow not applying changes from PR that got merged

### ISSUE THREAD

**Issue by Gregory-Pereira** [operate-first/common#101]
**Describe the bug**
I created a PR changing the `github-config.yaml` file to grant permissions, but the changes did not get applied by Prow. I went to take a look at [the logs](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/logs/operate-first-peribolos/1520082222831374336) and its saying that `"Configuration failed: failed to configure operate-first repo... The branch main was not found. Please push that ref first or create it via the Git Data API"`

**To Reproduce**
1. Go to `Operate-first/common`
2. Create a PR changing the permissions or any label, or simply view the Prow logs for an existing PR
3.  Check the logs for the `peribolos` check

**Expected behavior**
The ability to have permissions granted view Prow.

/cc @harshad16

**Comment by harshad16** [comment]
@Gregory-Pereira  is this still happening 
if it is not , please close this

**Comment by Gregory-Pereira** [comment]
Seeing as #145 's checks went through I am going to assume this is no longer an issue. Temporarily closing this issue, but will re-open if new evidence comes to light.
