### ISSUE TITLE
Generate `labels.md` in CI

### ISSUE THREAD

**Issue by tumido** [operate-first/common#11]
**Is your feature request related to a problem? Please describe.**
It's too tempting to edit `labels.md` manually, while it should be generated on the fly. Either as a CI check/pre-commit check or not present here and created for website only.

**Describe the solution you'd like**

Execute something analogical to:
```
podman run -it -v.:/mnt:Z gcr.io/k8s-prow/label_sync:latest --action=docs --config=/mnt/labels.yaml --docs-template=/mnt/labels.md.tmpl --docs-output=/mnt/labels.md
```

**Describe alternatives you've considered**
nah

**Additional context**
https://github.com/operate-first/common/pull/10
https://github.com/operate-first/common/pull/9

**Comment by schwesig** [comment]
/remove-lifecycle stale

Still not installed, I personally like it.
Let's see if we find somebody that likes to take care of it :-)
