### ISSUE TITLE
Instruction on how to create a new repo using the operate-first/template repo

### ISSUE THREAD

**Issue by HumairAK** [operate-first/common#52]
Currently a pr like this: https://github.com/operate-first/common/pull/51 doesn't use the operate-first/template, is this a default behavior we can enable somewhere? Or specify the template fork in an additional field? Investigate and update the docs accordingly.

**Comment by Gregory-Pereira** [comment]
I believe that it is possible but I think that it would require upstream contributions to Peribolos. Peribolos uses the [`configureOrg` function](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/main.go#L843) to call the [`configureRepos` function in the `main.go` file](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/main.go#L987-L1071), which finally calls the [`createRepo` function](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/main.go#L1036) available in [/prow/github of kubernetes/test-infra](https://github.com/kubernetes/test-infra/blob/6d1f472323d99e089d016718b77b15a2942d5d34/prow/github/client.go#L2465) if the repo doesn't exist and is not archived. This sends a request using the `https://developer.github.com/v3/repos/#create` endpoint according to the documentation, which has been moved, but as far as I can tell, docs for it now live [here](https://docs.github.com/en/rest/reference/repos#create-an-organization-repository). However, creating a repository from a template actually uses a different [GitHub endpoint](https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template). For this method, you call the `generate` endpoint of the repository where the template actually lives, and then additionally pass the `owner` and `name` for the repository you are creating, along with the aforementioned `template_owner` and `template_repo` to access it. It seems plausible to extend the [repository client](https://github.com/kubernetes/test-infra/blob/6d1f472323d99e089d016718b77b15a2942d5d34/prow/github/client.go#L161) with a`createRepoFromTemplate` function, and use the `github-config.yaml` to track the template repository, but maybe there is an easier way around this.
